/** YAML-matching session_* bounds. Auth cache-load abort uses these; do not clamp. */

export const SESSION_ACCESS_TTL_MIN = 60;
export const SESSION_ACCESS_TTL_DEFAULT = 900;
export const SESSION_ACCESS_TTL_MAX = 86400;

export const SESSION_REFRESH_TTL_MIN = 300;
export const SESSION_REFRESH_TTL_DEFAULT = 604800;
export const SESSION_REFRESH_TTL_MAX = 7776000;

export const SESSION_TOTAL_TTL_MIN = 300;
export const SESSION_TOTAL_TTL_DEFAULT = 2592000;
export const SESSION_TOTAL_TTL_MAX = 15552000;

export const SESSION_REFRESH_REUSE_GRACE_MIN = 5;
export const SESSION_REFRESH_REUSE_GRACE_DEFAULT = 15;
export const SESSION_REFRESH_REUSE_GRACE_MAX = 60;

export const SESSION_REFRESH_REUSE_WINDOW_MIN = 3600;
export const SESSION_REFRESH_REUSE_WINDOW_DEFAULT = 86400;
export const SESSION_REFRESH_REUSE_WINDOW_MAX = 604800;

export const SESSION_MAX_REFRESH_RETRIES_MIN = 1;
export const SESSION_MAX_REFRESH_RETRIES_DEFAULT = 5;
export const SESSION_MAX_REFRESH_RETRIES_MAX = 10;

export const SESSION_REFRESH_CLEANUP_MIN = 3600;
export const SESSION_REFRESH_CLEANUP_DEFAULT = 14400;
export const SESSION_REFRESH_CLEANUP_MAX = 259200;

export const SESSION_REFRESH_PROCESS_TIME_MINIMUM_MIN = 100;
export const SESSION_REFRESH_PROCESS_TIME_MINIMUM_DEFAULT = 300;
export const SESSION_REFRESH_PROCESS_TIME_MINIMUM_MAX = 500;

export const SESSION_REFRESH_PROCESS_TIME_MAXIMUM_MIN = 200;
export const SESSION_REFRESH_PROCESS_TIME_MAXIMUM_DEFAULT = 500;
export const SESSION_REFRESH_PROCESS_TIME_MAXIMUM_MAX = 1000;
